### ISSUE TITLE
Moving "AutoStop" function from VESC to Receiver 

### ISSUE THREAD

**Issue by looxis-renaud** [robertzach/ewinch_remote_controller#10]
Since the receiver has Tachometer Data through the UART connection and "knows" the line length,
why not move the "AutoSTOP" feature from the VESC to the Receiver?

The Receiver is already controlling the winch, why not also let it execute the AutoStop when the line has only ~15m left?

The advantage would be that we could use the latest VESC firmware, without having to constantly change it by adding the Autostop feature ( I can't get the modified firmware to run anyways, see #9 )

**Comment by robertzach** [comment]
It is already implemented it in the receiver code too (see line 277 to 292).
But it is slow (UART) and not 100% reliable (and you want 100%!).

See https://github.com/robertzach/ewinch_remote_controller/blob/main/receiver/receiver.ino:
      // auto line stop
      // (smouth to avoid line issues on main winch with rewinding winch)
      // tachometer > 2 --> avoid autostop when no tachometer values are read from uart (--> 0)
      if (vescUART.data.tachometer > 2 && vescUART.data.tachometer < 40) {
          if (targetPullValue > defaultPull){
              targetPullValue = defaultPull;
          }
          if (vescUART.data.tachometer < 20) {
              targetPullValue = softBrake;
          }
          if (vescUART.data.tachometer < 10) {
              targetPullValue = hardBrake;
          }
          Serial.println("Autostop active, target pull value:");
          Serial.println(targetPullValue);
      }
