### ISSUE TITLE
pinmode set for button up / dn

### ISSUE THREAD

**Issue by steve1428** [robertzach/ewinch_remote_controller#18]
hi can you tell me please if pin 15 / 12 are internal pullup?
I can't see in the code.

is it possible to change to internal pulldown so we can trigger it with an external 3.3V signal?

**Comment by robertzach** [comment]
yes, both use a internal pull up. I am not sure if you can reprogram it. Google is your friend :-).
Fast solutions would be a external 1k resistor to GND or use a different pin...
