### ISSUE TITLE
Motor

### ISSUE THREAD

**Issue by looxis-renaud** [robertzach/ewinch_remote_controller#3]
In one of the youtube comments you mentioned that you are using the QS Motor 12kw,
available here: https://www.aliexpress.com/item/4001237537247.html

Do you use the **"72V"** or the **"96V"** version ?

**Comment by robertzach** [comment]
Chinese supplier are a bit confusing with their order options.
The main thing is the "KV" value which describes the rpm / voltage relation.
rpm = KV * voltage

Therefore, it depends on what battery voltage you use.
With a 16s lion battery (what I use) you have around 16*3,7 --> 60V.
For this case I recommend the 72V option (72V @ 1047RPM --> KV = 14).

**Comment by steve1428** [comment]
be careful, I Found some other people representing themselves as QS motor when they weren't.  Deal with them directly.
I'm having a lot of trouble with line 29 in the reciever code
SSD1306 display(0x3c, 21, 22);
maybe I don't have the right SSD1306 libraries?
