### ISSUE TITLE
parts needed for controlling the brushless DC Motor?

### ISSUE THREAD

**Issue by looxis-renaud** [robertzach/ewinch_remote_controller#6]
watching your videos, I assume one needs the following electronics to control a brushless dc motor:

* VESC Controller
* Receiver: 1x LILYGO® TTGO ESP32-Paxcounter connected with VESC
* Transceiver 2x LILYGO® TTGO ESP32-Paxcounter, 1x Master & 1x Slave

Is this correct, or is anything else needed?

![winch-schema](https://user-images.githubusercontent.com/16876388/190900765-39438f24-3a97-4413-af06-35fda0811ef1.jpg)

**Comment by robertzach** [comment]
basically yes.
If multiple transmitter are used I would describe it as "admin" and "user" transmitters...
